kafka:
  bootstrapAddress: localhost:9092
  topic:
    playground: playground.topic
    deadletter:
      suffix:
        recoverable: .recoverable.dlt
        unrecoverable: .unrecoverable.dlt
  groupId: playground-1